# Generated by Django 5.0.6 on 2024-06-30 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 1, 14, 38, 28, 511472, tzinfo=datetime.timezone.utc)),
        ),
    ]
