# Generated by Django 5.0.6 on 2024-07-10 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailverification_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 14, 51, 13, 439346, tzinfo=datetime.timezone.utc)),
        ),
    ]
