# Generated by Django 5.0.6 on 2024-07-10 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_emailverification_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 11, 15, 30, 31, 31941, tzinfo=datetime.timezone.utc)),
        ),
    ]
